import { Event, EventType } from '@/lib/types/meetup';

// Collection of all ETH Bologna events
export const events: Event[] = [
  {
    id: 16,
    title: 'ETH Bologna #16',
    date: '2025-12-18',
    time: '19:30',
    location: 'To be defined',
    description: 'Details coming soon for ETH Bologna #18!',
    type: EventType.MEETUP,
  },
  {
    id: 15,
    title: 'ETH Bologna #15',
    date: '2025-11-20',
    time: '19:30',
    location: 'To be defined',
    description: 'Details coming soon for ETH Bologna #17!',
    type: EventType.MEETUP,
  },
  {
    id: 14,
    title: 'ETH Bologna #14',
    date: '2025-10-24',
    time: '19:30',
    location: 'To be defined',
    description: 'Details coming soon for ETH Bologna #16!',
    type: EventType.MEETUP,
  },
  {
    id: 13,
    title: 'ETH Bologna #13',
    date: '2025-09-25',
    time: '19:30',
    location: 'To be defined',
    description: 'Details coming soon for ETH Bologna #15!',
    type: EventType.MEETUP,
  },
  {
    id: 12,
    title: 'ETH Bologna #12',
    date: '2025-07-24',
    time: '19:30',
    location: 'To be defined',
    description: 'Details coming soon for ETH Bologna #13!',
    type: EventType.MEETUP,
  },
  {
    id: 11,
    title: 'ETH Bologna #11',
    date: '2025-06-19',
    time: '19:30',
    location: 'To be defined',
    description: 'Details coming soon for ETH Bologna #12!',
    type: EventType.MEETUP,
  },
  {
    id: 10,
    title: 'ETH Bologna #10',
    date: '2025-04-24',
    time: '19:30',
    location: 'To be defined',
    description: 'Details coming soon for ETH Bologna #10!',
    type: EventType.MEETUP,
  },
  {
    id: 9,
    title: 'ETH Bologna #9',
    date: '2025-03-28',
    time: '19:30',
    location: 'To be defined',
    description: 'Details coming soon for ETH Bologna #9!',
    type: EventType.MEETUP,
  },
  {
    id: 8,
    title: 'ETH Bologna #8',
    date: '2025-02-20',
    time: '19:30',
    location: 'To be defined',
    description: 'Details coming soon for ETH Bologna #8!',
    type: EventType.MEETUP,
  },
  {
    id: 7,
    title: 'ETH Bologna #7',
    date: '2025-01-23',
    time: '19:30',
    location: 'Osteria La Frasca al Vicolo',
    description:
      "Join us for our first meetup of 2025 at the historic Osteria La Frasca al Vicolo, nestled in the heart of Bologna.",
    type: EventType.MEETUP,
  },
  {
    id: 6,
    title: 'ETH Bologna #6',
    date: '2024-05-23',
    time: '19:30',
    location: 'To be defined (Probably the Funtanir)',
    description: 'To be defined the meeting venue!',
    type: EventType.MEETUP,
  },
  {
    id: 5,
    title: 'ETH Bologna #5',
    date: '2024-04-30',
    time: '19:30',
    location: 'Remote',
    description: 'Check telegram for the meeting link',
    type: EventType.ONLINE,
  },
  {
    id: 4,
    title: 'ETH Bologna #4',
    date: '2024-04-18',
    time: '19:30',
    location: 'Funtanir Bistrò Cocktail & Rooms',
    description: 'Join us at Via Riva di Reno 47a, Bologna, 40122',
    type: EventType.MEETUP,
    link: 'https://www.eventbrite.com/e/biglietti-ethbologna-4-865075182157?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl',
  },
  {
    id: 3,
    title: 'ETH Bologna #3',
    date: '2024-03-12',
    time: '19:30',
    location: 'Huhcocktail',
    description: 'Join us at Piazza San Francesco 10g, 40122 Bologna',
    type: EventType.MEETUP,
  },
  {
    id: 2,
    title: 'ETH Bologna #2',
    date: '2024-01-25',
    time: '18:00',
    location: 'Funtanir Bistrò Cocktail & Rooms',
    description:
      'Join us at Via Riva di Reno 47a, Bologna, 40122. Check on Telegram for more details.',
    type: EventType.MEETUP,
  },
  {
    id: 1,
    title: 'ETH Bologna #1',
    date: '2023-12-18',
    time: '19:30',
    location: 'Cluricaune Irish Pub',
    description:
      'Join us at Via Zamboni 18b, 40126, Bologna. Check on telegram for more details.',
    type: EventType.MEETUP,
  },
  {
    id: 0,
    title: 'ETH Bologna #0',
    date: '2023-12-07',
    time: '19:30',
    location: 'TBD',
    description: 'Meetups coming very soon.',
    type: EventType.MEETUP,
  },
];
